# below are all optional configurations. if there is a value present, that is
# the default value. to override a value, change it and uncomment that line of
# the config.

# server:
#   addr: 127.0.0.1:8080
#   tls-cert:
#   tls-key:
#   tls-ca:
# datatsource:
#   url: localhost
#   database: etre
#   timeout: 5
#   tls-cert:
#   tls-key:
#   tls-ca:
#   username:
#   source:
#   mechanism:
# entity:
#   entity_types:
#     - nodes
# cdc:
#   collection: cdc
#   fallbackFile:
#   write_retry_count: 3
#   write_retry_wait_ms = 50
# delay:
#   collection: delay
#   static_delay_ms: -1
